spring:
  profiles:
    active: dev_loc

---
server:
  port: 9999
spring:
  application:
    name: store-test
  profiles: dev_loc   # 本地测试
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

---
server:
  port: 9999
spring:
  application:
    name: store-test
  profiles: dev_remote   # 本地测试
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.0.57:8848