spring:
  profiles:
    active: dev

---
server:
  port: 6001

spring:
  application:
    name: store-auth
  profiles: dev
  redis:
    database: 1
    host: 127.0.0.1
    password: 123456
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
